### ISSUE TITLE
Doesn't sending filters data

### ISSUE THREAD

**Issue by rilysh** [XzFirzal/lavacoffee#8]
Just tried lavacoffee filters feature, but it seems like lavacoffee doesn't sending filters data to lavalink server, for sure tried [this](https://azusfin.github.io/lavacoffee/index.html#filters) example, but nope. Checked lavalink logs as well, doesn't seems to be.
![image](https://user-images.githubusercontent.com/71683721/153555501-856d4ccd-7e7e-4b0c-9a52-9b5ec04459a6.png)

**Comment by Azusfin** [comment]
do you also have
```js
player.patchFilters()
```
?
